"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8%4ip8fm+gc9(@0%jnkbb*-l08(!8qeccedfzl#dxamuiyfh$*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'oauth2_provider',
    'drf_yasg',


    'apps.account',
    'apps.cart',
    'apps.catalog',
    'apps.order',
    'apps.review',
    'apps.voucher',
    'apps.notification',
    'apps.report'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'shoppingdb',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': ''  # mặc định localhost
    }
}

AUTH_USER_MODEL = 'account.User'

import pymysql

pymysql.version_info = (2, 2, 1, 'final', 0)
pymysql.install_as_MySQLdb()

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CLIENT_ID = 'j4lfSoXaX4Cn6lWelukitumNgO2YjqXSZGWNu8nk'
CLIENT_SECRET = 'TxFQqpyEAjVt5hTbmvorQQ1ZwM7gYSpOhrD3YWTe5EMcND0Jpw2DkefnPEPOe8Dj2z7rWskNLSIaByk8REbCzloA7aBGZ4fmeJS5S46HT9Bhg5wgc0LgsFCxDoZlxDan'

# Cấu hình MoMo Sandbox
MOMO_PARTNER_CODE = "MOMOBKUN20180529" # Thay bằng mã của bạn
MOMO_ACCESS_KEY = "klm05TvNCyandm2Z"   # Thay bằng key của bạn
MOMO_SECRET_KEY = "at67qH6mk8g5i1Pe1JzJWFAoa4syVw=" # Thay bằng secret của bạn
MOMO_ENDPOINT = "https://test-payment.momo.vn/v2/gateway/api/create"

# Khách thanh toán xong sẽ được MoMo chuyển hướng về trang này (Frontend của bạn)
MOMO_REDIRECT_URL = "http://localhost:3000/order/success"
# Domain thật hoặc Ngrok của Backend để MoMo có thể gọi IPN (Webhook) cập nhật trạng thái
MOMO_IPN_URL = "https://<your-ngrok-domain>/order/orders/momo_webhook/"
